language: java

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
    webhooks: https://www.travisbuddy.com/

deploy:
  provider: script
  script:
  on:
    tags: true
