language: java

# Travis is configured to run on pushed branches and pull requests so if we don't filter branches it runs twice when
# we push the PR branch in our repo
branches:
  only:
    - master
    #tag xx.yy-zz or xx.yy.zz-anythinglikeexperimental
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
    #hotfix branches (not being too strict on purpose)
    - /^hf-\.*$/

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
    # enables comments in the branch with the CI results
    webhooks: https://www.travisbuddy.com/

deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    tags: true
